- name: Kiosk
  hosts: all
  vars: { ansible_user_id: suhlig }
  pre_tasks:
    - name: Program snapshot is up to date
      local_action:
        module: ansible.builtin.command
        cmd: goreleaser --snapshot --clean
        args:
          chdir: "{{ playbook_dir }}"
      become: false
    - name: Path to binary is set from artifacts.json
      ansible.builtin.set_fact:
        binary_path: "{{ item['path'] }}"
      when: |
        item['goos'] is defined and item['goos'] == 'linux'
        and item['goarch'] is defined and item['goarch'] == 'arm'
        and item['goarm'] is defined and item['goarm'] == '7'
        and item['type'] is defined and item['type'] == 'Binary'
      loop: "{{ lookup('file', playbook_dir + '/dist/artifacts.json') | from_json }}"
      tags: [ kiosk, goreleaser, binary, path, artifacts ]
  tasks:
    - name: Config file is present
      become: true
      copy:
        src: kiosk.yml
        dest: /etc/kiosk.yml
        mode: '0644'
        owner: "{{ ansible_user_id }}"
      register: config_copied
      tags: [ kiosk, yaml, config ]
    - name: Service is restarted
      systemd:
        name: kiosk
        state: restarted
      when: config_copied.changed
      tags: [ kiosk, config, systemd, service ]
  roles:
    - role: kiosk
      become: true
      tags: [ kiosk, software ]
    - role: suhlig.simple_systemd_service
      become: true
      vars:
        systemd:
          target: graphical.target
        service_binary: kiosk
        program:
          name: kiosk
          description: Display kiosk
          runtime_user: "{{ ansible_user_id }}"
          binary: "{{ binary_path }}"
          parameters:
            - --kiosk
            - --verbose
            - --interval 10s
            - --http-address :8011
            - --chrome-flag window-position=800,0
            - /etc/kiosk.yml
          environment:
            DISPLAY: ":0.0"
            MQTT_URL: "{{ mqtt_url }}"
      tags: [ kiosk, systemd, service ]
