---
- name: Kiosk
  hosts: all
  remote_user: pi

  roles:
    - common
    - kiosk
    - wifi
    - { role: geerlingguy.ntp, become: true }
    - { role: jnv.unattended-upgrades, become: true }

  vars:
    hostname: kiosk
    kiosk_url: http://pairadi.se

    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

    unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
    unattended_automatic_reboot_time: "04:11"
