- name: Install common software
  apt:
    name:
      - ttf-mscorefonts-installer
      - unclutter
      - xdotool
    state: present
    update_cache: yes
  tags: apt, kiosk

- name: Unwanted software is not present
  apt:
    name:
      - libreoffice*
    state: absent
  tags: apt, kiosk

- name: Chromium policy is in place
  copy:
    src: no-password-management.json
    dest: /etc/chromium/policies/managed/
  tags: chromium, kiosk, policy
