- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  become: true
  tags: hostname,dns

- name: Replace "rasp.*" with new hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\\.0\\.0\\.1\\s+rasp.*'
    line: "127.0.0.1  {{ hostname }}"
  notify:
    - restart systemd-logind
  become: true
  tags: hostname,dns

- name: Install common software
  apt:
    name:
      - tmux
      - htop
      - vim
    state: present
    update_cache: yes
  become: true
  tags: apt

- name: Always start the ssh service
  systemd:
    name: ssh
    state: started
    enabled: true
  become: true

- name: No stupid login message
  file:
    path:  /home/pi/.hushlogin
    state: touch
    owner: pi
    group: pi
    mode:  "0755"

- name: Set keyboard layout to DE
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: true
